// <auto-generated />
using Discount.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Discount.API.Migrations
{
    [DbContext(typeof(DiscountContext))]
    partial class DiscountContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("Discount.API.Models.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsGlobal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Coupon", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 10.0,
                            Description = "Promo IPhone",
                            IsGlobal = false,
                            ProductName = "IPhone X",
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Amount = 50.0,
                            Description = "Promo Samsung",
                            IsGlobal = false,
                            ProductName = "Samsung 10",
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            Amount = 5.0,
                            Description = "Code promo global -5%",
                            IsGlobal = true,
                            ProductName = "",
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            Amount = 10.0,
                            Description = "Bon de reduction 10 euros",
                            IsGlobal = true,
                            ProductName = "",
                            Type = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
